@node О демоне
@unnumbered Подробнее о демоне GoVPN

GoVPN это простой демон виртуальных частных сетей, код которого нацелен
на лёгкость чтения и анализа, безопасность, устойчивость к DPI/цензуре.

@itemize
@item
Свободное программное обеспечение, копилефт: лицензировано под условиями
@url{https://www.gnu.org/licenses/gpl-3.0.ru.html, GPLv3+}.
@item
Быстрый сильный аутентифицируемый по парольной фразе несбалансированный
протокол согласования ключей с двусторонней аутентификацией сторон и
нулевым неразглашением (PAKE DH A-EKE (Diffie-Hellman Augmented
Encrypted Key Exchange)).
@item
Несбалансированные аутентификационные токены устойчивые к внесетевым
(offline) атакам по словарю. Используют усиленный по CPU и памяти
алгоритм хэширования. Злоумышленник не может замаскироваться под
клиента даже скомпрометировав базу данных токенов сервера.
@item
Зашифрованный и аутентифицируемый транспортный протокол передачи данных
с 128-бит порогом безопасности и современной криптографией.
@item
Цензуроустойчивые сообщения транспорта и рукопожатия: неотличимые от
шума с опциональным скрытием размеров сообщений.
@item
Свойство совершенной прямой секретности (perfect forward secrecy).
@item
Защита от атак повторного воспроизведения (replay) (используя
одноразовые MAC).
@item
Встроенные функции пересогласования ключей (ротация сессионных ключей) и 
сердцебиения (heartbeat).
@item
Возможность скрывать размеры пакетов путём зашумления данных.
@item
Возможность скрывать временные характеристики полезной нагрузки путём
постоянного по скорости трафика.
@item
Совместимость с @url{http://egd.sourceforge.net/, EGD} (демон сборки
энтропии) генераторами псевдослучайных чисел.
@item
Поддержка нескольких клиентов одновременно с специфичной для каждого
конфигурацией. Клиенты имеют заранее установленный идентификатор,
невидимый третьим лицам (они анонимны для них).
@item
Использует TAP низлежащие сетевые интерфейсы.
@item
Может работать поверх UDP, TCP и HTTP прокси для доступа к серверу.
@item
Полностью IPv4 и IPv6 совместимый.
@item
Опциональный встроенный HTTP-сервер для получения статистики о
подключённых клиентах в режиме реального времени в JSON формате.
@item
Написан на языке Go с простым кодом, ориентированным на лёгкость чтения
и анализа.
@item
Поддержка GNU/Linux и FreeBSD.
@end itemize
