@node Reporting bugs
@unnumbered Reporting bugs

Please send all questions, bug reports and patches to to
@email{govpn-devel@@lists.cypherpunks.ru} mailing list.
Also it is used for announcements.

Either visit @url{https://lists.cypherpunks.ru/mailman/listinfo/govpn-devel}
for information about subscription options and archived messages access, or
send email with the subject @code{subscribe} to
@email{govpn-devel-request@@lists.cypherpunks.ru}.

Official website is @url{http://www.cypherpunks.ru/govpn/}, also available
as @url{https://www.torproject.org/, Tor} hidden service:
@url{http://vabu56j2ep2rwv3b.onion/govpn/}.
Development Git source code repository currently is located here:
@url{https://github.com/stargrave/govpn.git}.
