@node Client
@section Client part

Except for common @code{-mtu}, @code{-stats}, @code{-egd}
options client has the following ones:

@table @code

@item -proto
@ref{Network, network protocol} to use. Can be either @emph{udp}
(default) or @emph{tcp}.

@item -proxy
Use specified @emph{host:port} @ref{Proxy} server for accessing remote
server.

@item -proxy-auth
Optional @emph{user:password} for HTTP Basic authorization on proxy
server.

@item -remote
Address (@code{host:port} format) of remote server we need to connect to.

@item -iface
TAP interface name.

@item -verifier
Our client's @ref{Verifier}.

@item -key
Path to the file with the passphrase. See @ref{Verifier} for
how to enter passphrase from stdin silently and store it in the file.

@item -timeout
@ref{Timeout} setting in seconds.

@item -noise
Enable @ref{Noise}.

@item -cpr
Set @ref{CPR} in KiB/sec.

@item -up
Optional path to script that will be executed after connection is
established. Interface name will be given to it as a first argument.

@item -down
Same as @code{-up} above, but it is executed when connection is lost,
when we exit.

@end table

Example up-script that calls DHCP client and IPv6 advertisement
solicitation:

@example
client% cat > up.sh <<EOF
#!/bin/sh
dhclient $1
rtsol $1
EOF
client% chmod +x up.sh
@end example
