@node Developer manual
@unnumbered Developer manual

@table @asis
@item Nonce and identification encryption
@url{http://143.53.36.235:8080/tea.htm, XTEA}
@item Data encryption
@url{http://cr.yp.to/snuffle.html, Salsa20}
@item Message authentication
@url{http://cr.yp.to/mac.html, Poly1305}
@item Password authenticated key agreement
DH-EKE powered by @url{http://cr.yp.to/ecdh.html, Curve25519}
@item Packet overhead
26 bytes per packet
@item Handshake overhead
4 UDP (2 from client, 2 from server) packets, 200 bytes total payload
@end table

@menu
* Transport protocol::
* Handshake protocol::
@end menu

@include transport.texi
@include handshake.texi
