@node Glossary
@section Glossary

@menu
* Entropy gathering daemon: EGD.
* Identity::
* Password Authenticated Key Agreement: PAKE.
* Timeout::
* Network transport: Network.
* Proxy::
* Maximum Transmission Unit: MTU.
* Statistics: Stats.
* Noise::
* Constant Packet Rate: CPR.
* Verifier::
@end menu

@include egd.texi
@include identity.texi
@include pake.texi
@include timeout.texi
@include netproto.texi
@include proxy.texi
@include mtu.texi
@include stats.texi
@include noise.texi
@include cpr.texi
@include verifier.texi
