\input texinfo
@setfilename govpn.info
@documentencoding UTF-8
@settitle GoVPN

@copying
@quotation
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
@end quotation
@end copying

@node Top
@top GoVPN

This manual is for GoVPN -- simple secure free software virtual private
network (VPN) daemon, written entirely on Go programming language.

@menu
* Overview::
* News::
* Installation::
* Precautions::
* User manual::
* Developer manual::
* Reporting bugs::
* Copying conditions::
@end menu

@include overview.texi

@node News
@unnumbered News

@verbatiminclude ../NEWS

@include installation.texi

@include precautions.texi

@include user.texi

@include developer.texi

@include bugs.texi

@node Copying conditions
@unnumbered Copying conditions

@insertcopying

@bye
