@node Identity
@section Identity

Client's identity is 128-bit string. It is not secret, so can be
transmitted and stored in the clear. However handshake applies PRP on it
to make DPI and deanonymization much harder to success.

@example
% ./utils/newclient.sh doesnotmatter
Place verifier to peers/6d4ac605ce8dc37c2f0bf21cb542a713/verifier
@end example

"6d4ac605ce8dc37c2f0bf21cb542a713" is client's identity.
