@node Installation
@unnumbered Installation

GoVPN is written on @url{http://golang.org/, Go programming language},
@emph{Make} is recommended for convenient building.
@url{https://www.gnu.org/software/texinfo/, Texinfo}
is used for building documentation.

Included required libraries:

@multitable @columnfractions .40 .20 .40
@headitem Library @tab Platform @tab Licence
@item @code{golang.org/x/crypto} @tab All @tab BSD 3-Clause
@item @code{github.com/agl/ed25519} @tab All @tab BSD 3-Clause
@item @code{github.com/bigeagle/water} @tab GNU/Linux @tab BSD 3-Clause
@end multitable

Get the tarball and run @code{make}.
@emph{govpn-client}, @emph{govpn-server}, @emph{govpn-verifier}
binaries will be build in the current directory.

@example
% wget http://www.cypherpunks.ru/govpn/download/govpn-2.3.tar.xz
% wget http://www.cypherpunks.ru/govpn/download/govpn-2.3.tar.xz.sig
% gpg --verify govpn-2.3.tar.xz.sig govpn-2.3.tar.xz
% tar xf govpn-2.3.tar.xz
% make -C govpn-2.3 all
@end example

@menu
* Prepared tarballs::
* Development source code::
* Tarballs integrity check::
@end menu

@include download.texi
@include sources.texi
@include integrity.texi
