@node MTU
@subsection Maximum Transmission Unit

MTU option tells what maximum transmission unit is expected to get from
TAP interface. It is per-user configuration. If the program gets bigger
size packet (including the padding byte), then it will ignore that
packet. If either @ref{Noise, noise}, or @ref{CPR} are enabled, then all
outgoing packets are filled up to that MTU value.

Default MTU equals to 1514 bytes (1500 bytes of Ethernet payload, 14
bytes of Ethernet header).
