@node User manual
@unnumbered User manual

Announcements about updates and new releases can be found in
@ref{Reporting bugs}.

GoVPN is split into two pieces: client and server. Each of them work on
top of UDP and TAP virtual network interfaces. GoVPN is just a
tunnelling of Ethernet frames, nothing less, nothing more. All you
IP-level network management is not touched by VPN at all. You can
automate it using up and down shell scripts.

@menu
* Timeout::
* Nonce difference::
* MTU::
* Client part::
* Server part::
* Stats::
* Noise::
* CPR::
* Example usage::
@end menu

@include timeout.texi

@include noncediff.texi

@include mtu.texi

@include client.texi

@include server.texi

@include stats.texi

@include noise.texi

@include cpr.texi

@include example.texi
