@node User manual
@unnumbered User manual

Announcements about updates and new releases can be found in @ref{Contacts}.

GoVPN is split into two pieces: client and server. Each of them work on
top of UDP and TAP virtual network interfaces. GoVPN is just a
tunnelling of Ethernet frames, nothing less, nothing more. All you
IP-related network management is not touched by VPN at all. You can
automate it using up and down shell scripts.

@menu
* EGD:: Entropy gathering daemon
* Identity::
* PAKE:: Password Authenticated Key Agreement
* Timeout::
* MTU:: Maximum Transmission Unit
* Stats::
* Noise::
* CPR:: Constant Packet Rate
* Verifier::
* Client part::
* Server part::
* Example usage::
@end menu

@include egd.texi
@include identity.texi
@include pake.texi
@include timeout.texi
@include mtu.texi
@include stats.texi
@include noise.texi
@include cpr.texi
@include verifier.texi
@include client.texi
@include server.texi
@include example.texi
